# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Shell-Base
version:      0.04
version_from: 
installdirs:  site
requires:
    Carp:                          0
    Env:                           0
    IO::File:                      0
    Term::ReadLine:                0
    Term::Size:                    0.2
    Text::Shellwords:              0
    Text::Wrap:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
